version: '3.9'

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: simple-blog
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
